config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
    end
  end

  resources :stories do
    member do
      get  :upvote, :downvote
    end
    resources :comments do
      member do
        get :upvote, :downvote
      end
    end
  end

  resources :comments do
    member do
      get :approve, :reject
    end
    collection do
      get :index
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy] do
    collection do
      get :forgot_password, :new_password, :update_reset_password
      post :send_reset_password, :reset_new_password
    end
  end
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
  root :to => "pages#home"

   match '/unsigned_retiree', :to => 'pages#unsigned_retiree'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/poststory', :to => 'pages#poststory'
  match '/postcomment', :to => 'comments#create'
  match '/retiree', :to => 'retirees#index'

  resources :retirees do
    collection do
      post :find_retiree
    end
  end
  get "retiree/index"
  get "retiree/update"
  get "retiree/delete"
  get "retiree/create"
  get "comments/create"
  get "comments/destroy"
  get "comments/show"

end

app/models/retiree.rb
class Retiree < ActiveRecord::Base
  has_attached_file :photo,
    :styles =>{
            :thumb=>"100x100#",
            :small=>"400x400"}

  belongs_to :user
end

app/controllers/retirees_controller.rb
require 'application_constant'
class RetireesController < ApplicationController
  
  # GET /retirees
  # GET /retirees.xml
  def index
   # @retirees = Retiree.all
    @retirees = Retiree.paginate(:page => params[:page], :per_page => ApplicationConstant::PER_PAGE,
                                 :order => 'created_at DESC')
     @retirees_sample = Retiree.all( :order => 'created_at DESC', :limit => 4)
    @title = "Retiree wisdom"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @retirees }
    end
  end

  def find_retiree
    @retirees = Retiree.paginate(:conditions => ["first_name LIKE ? OR last_name like ? OR years_worked = ?", params[:retiree][:name],params[:retiree][:name],params[:retiree][:name]], :page => params[:page], :per_page => ApplicationConstant::PER_PAGE,
                                 :order => 'created_at DESC')
    @title = "Found #{@retirees.size.to_s} results "

    respond_to do |format|
      format.html {render :action => :index}
      format.xml  { render :xml => @retirees }
    end
  end

  # GET /retirees/1
  # GET /retirees/1.xml
  def show
    @retiree = Retiree.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @retiree }
    end
  end

  # GET /retirees/new
  # GET /retirees/new.xml
  def new
    @retiree = Retiree.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @retiree }
    end
  end

  # GET /retirees/1/edit
  def edit
    @retiree = Retiree.find(params[:id])
  end

  # POST /retirees
  # POST /retirees.xml
  def create
    @retiree = Retiree.new(params[:retiree])
    @retiree.user_id = current_user.id
    respond_to do |format|
      if @retiree.save
         flash[:notice] =  'Retiree was successfully created.'
        format.html { redirect_to(:action=>"show", :controller=>"retirees", :id=>@retiree.id) }
        format.xml  { render :xml => @retiree, :status => :created, :location => @retiree }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @retiree.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /retirees/1
  # PUT /retirees/1.xml
  def update
    @retiree = Retiree.find(params[:id])

    respond_to do |format|
      if @retiree.update_attributes(params[:retiree])
        format.html { redirect_to(@retiree, :notice => 'Retiree was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @retiree.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /retirees/1
  # DELETE /retirees/1.xml
  def destroy
    @retiree = Retiree.find(params[:id])
    @retiree.destroy

    respond_to do |format|
      format.html { redirect_to(retirees_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/retiree_helper.rb
module RetireeHelper
end

app/helpers/retirees_helper.rb
module RetireesHelper
end

app/views/retirees/_form.html.erb
<div class="round" style="background-color: lightgray;width:70%;padding:5%;">
<%= form_for @retiree, :html => { :multipart => true } do |f| %>
  <% if @retiree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retiree.errors.count, "error") %> prohibited this retiree from being saved:</h2>
      <ul>
      <% @retiree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td> <%= f.label :user_id %></td>
      <td><%= f.text_field :user_id %></td>
    </tr>
    <tr>
      <td> <%= f.label :first_name %></td>
      <td><%= f.text_field :first_name %></td>
    </tr>
   <tr>
      <td><%= f.label :last_name %></td>
      <td><%= f.text_field :last_name %></td>
    </tr>
       <tr>
      <td><%= f.label :years_worked %></td>
      <td><%= f.text_field :years_worked %></td>
    </tr>
    <tr>
      <td><%= f.label :plant %></td>
      <td><%= f.text_field :plant %></td>
    </tr>
    <tr>
      <td><%= f.label :pet_story %></td>
      <td><%= f.text_field :pet_story %></td>
    </tr>
    <tr>
      <td><%= f.label :what_are_you_doing %></td>
      <td><%= f.text_field :what_are_you_doing %></td>
    </tr>
   <!-- <tr>
      <td><%= f.label :video_path1 %></td>
      <td><%= f.text_field :video_path1 %></td>
    </tr> -->
    <tr>
      <td><%= f.label :message_to_company %></td>
      <td><%= f.text_field :message_to_ceo %></td>
    </tr>
    <tr>
      <td> <%= f.label :photo %></td>
      <td><%= f.file_field :photo %></td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>

app/views/retirees/edit.html.erb
<h1>Editing retiree</h1>

<%= render 'form' %>

<%= link_to 'Show', @retiree %> |
<%= link_to 'Back', retirees_path %>

app/views/retirees/index.html.erb
<div>  
</div>
<table> <tr><td> <% form_for :retiree, :url => find_retiree_retirees_path do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Search" %>
  <% end %></td><td><%= link_to 'Add Retiree', new_retiree_path, :class =>"addretiree_button" %></td></tr>
<tr><td><h4>Retired autoworkers with wisdom to share</h4></td></tr>
</table>
<table cellspacing="0" cellpadding="0" class="pretty-table">
 <thead>
    <tr>
            <th scope="col">Name</th>
            <th scope="col">Years worked</th>
            <th scope="col">Pet Story</th>
            <th scope="col">What are U doing now</th>
            <th scope="col">Message to Company</th>
    </tr>
</thead>
<tbody>
  <% @temp_retirees
     if signed_in? then
    @temp_retirees = @retirees
       else
   @temp_retirees =  @retirees_sample
  end %>

   <%  @temp_retirees.each do |retiree| %>

<tr>
   <% if retiree.photo.exists? then%>
        <th scope="row"><%=image_tag retiree.photo.url(:thumb), :alt => "autoworker",  :size=>"70x70" %> <%= retiree.first_name %> <%= retiree.last_name %></th>
        <% else %>
        <th scope="row"><%=image_tag("retiredaw2.jpg", :size=>"70x70", :alt => "autoworker") %></br><%= retiree.first_name %> <%= retiree.last_name %></th>
        <% end %>

  <!--    <th scope="row"><img alt="" src="http://www.musicrooms.net/thumbnail.php?file=artists/jermaine_jackson_226268685.jpg"><%= retiree.first_name %> <%= retiree.last_name %></th> -->
      <td><%= retiree.years_worked %> years at <%= retiree.plant %></td>
      <td><%= retiree.pet_story %> </td>
      <td><%= retiree.what_are_you_doing %></td>
      <td><%= retiree.message_to_ceo %> </td>
</tr>
</tbody>
 <!--   <tr>
              
        <td><%= link_to 'Edit', edit_retiree_path(retiree) if current_user == retiree.user %></td>
             <% if false %>
            <td><%= link_to 'Show', retiree %></td>
            <td><%= link_to 'Destroy', retiree, :confirm => 'Are you sure?', :method => :delete %></td>
          <% end %>
    </tr> -->
  <% end %>
 <% $end %>
  <%= will_paginate @retirees %>
</table>
 <% if not signed_in? %>
    <%=  link_to "sign in to view more retirees", signin_path, :class =>"addretiree_button2" %>
 <% end %>

app/views/retirees/indindex_good.html.erb
<div>
  <% form_for :retiree, :url => find_retiree_retirees_path do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Search" %>
  <% end %>
  <%= link_to 'Add Retiree', new_retiree_path %>
</div>
<h3>Retired Autoworkers with wisdom to share</h3>
<table>
  <tr>
    <th class="retiree_th round"> &nbsp;</th>
    <th class="retiree_th round"> Name</th>
    <th class="retiree_th round">Years</th>
    <th class="retiree_th round">Pet Story</th>
    <th class="retiree_th round">Current Hobby</th>
    <th class="retiree_th round">Ceo's Message</th>
    <!--<th>Status</th>
    <th>Message to CEO</th>
    <th></th>
    <th></th>
    <th></th-->
  </tr>

  <% @retirees.each do |retiree| %>
    <tr>
      <% if retiree.photo.exists? then%>
        <td><%=image_tag retiree.photo.url(:thumb) %> </td>
        <% else %>
        <td><%=image_tag("logo3.jpeg") %></td>
        <% end %>
      <td class="retiree_experience round"><%= retiree.first_name %> <%= retiree.last_name %></td>
      <td class="retiree_experience round"><%= retiree.years_worked %> years at <%= retiree.plant %></td>
      <td class="retiree_petstory round"><%= retiree.pet_story %></td>
      <td class="retiree_status round"><%= retiree.what_are_you_doing %></td>
      <td class="retiree_ceomsg round"><%= retiree.message_to_ceo %></td>

     
        
        <td><%= link_to 'Edit', edit_retiree_path(retiree) if current_user == retiree.user %></td>
         <% if false %>
        <td><%= link_to 'Show', retiree %></td>
        <td><%= link_to 'Destroy', retiree, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
  <%= will_paginate @retirees %>
</table>

app/views/retirees/new.html.erb
<h1>New retiree</h1>
<%= render 'form' %>
<%= link_to 'Back', retirees_path %>

app/views/retirees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @retiree.user_id %>
</p>

<p>
  <b>First name:</b>
  <%= @retiree.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @retiree.last_name %>
</p>

<p>
  <b>Years worked:</b>
  <%= @retiree.years_worked %>
</p>

<p>
  <b>Plant:</b>
  <%= @retiree.plant %>
</p>

<p>
  <b>Pet story:</b>
  <%= @retiree.pet_story %>
</p>

<p>
  <b>What are you doing:</b>
  <%= @retiree.what_are_you_doing %>
</p>

<p>
  <b>Photo path1:</b>
  <%= @retiree.photo_path1 %>
</p>

<p>
  <b>Video path1:</b>
  <%= @retiree.video_path1 %>
</p>

<p>
  <b>Message to ceo:</b>
  <%= @retiree.message_to_ceo %>
</p>


<%= link_to 'Edit', edit_retiree_path(@retiree) %> |
<%= link_to 'Back', retirees_path %>