config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
    end
  end

  resources :stories do
    member do
      get  :upvote, :downvote
    end
    resources :comments do
      member do
        get :upvote, :downvote
      end
    end
  end

  resources :comments do
    member do
      get :approve, :reject
    end
    collection do
      get :index
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy] do
    collection do
      get :forgot_password, :new_password, :update_reset_password
      post :send_reset_password, :reset_new_password
    end
  end
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
  root :to => "pages#home"

   match '/unsigned_retiree', :to => 'pages#unsigned_retiree'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/poststory', :to => 'pages#poststory'
  match '/postcomment', :to => 'comments#create'
  match '/retiree', :to => 'retirees#index'

  resources :retirees do
    collection do
      post :find_retiree
    end
  end
  get "retiree/index"
  get "retiree/update"
  get "retiree/delete"
  get "retiree/create"
  get "comments/create"
  get "comments/destroy"
  get "comments/show"

end

app/models/comment.rb
require 'application_constant'
class Comment < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  attr_accessible :comment_text
  before_save :validate_comment_text

  APPROVED = 1
  REJECTED = 2
  DEFAULT = 0

  validates :comment_text, :presence => true, :length => { :maximum => 1000 }
  # validates :user_id, :presence => true
  validates :story_id, :presence => true

  scope :moderated, lambda {|num|
    where("(comments.moderated = 1 OR comments.moderated = 0 ) AND comments.story_id = ?", num)
  }

  def validate_comment_text
    #Find if a word is there
    ApplicationConstant::ABUSIVE.each do |word|
      self.comment_text.gsub!(/#{word.to_s}/, "****") if self.comment_text.include?(word.to_s)
    end
  end


  def upvote
    self.increment!(:votes)
  end

  def downvote
    self.decrement!(:votes)
  end

  def approved
    self.update_attribute(:moderated, Comment::APPROVED)
  end

  def rejected
    self.update_attribute(:moderated, Comment::REJECTED)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate
  before_filter :find_comment, :only => [:upvote, :downvote,]

  def index
    #@comments = Comment.find(:all, :conditions => {:moderated => 0})
    @comments = Comment.find(:all)
  end

#  def approve
#    @comment.approved
#    flash[:success] = "comment Moderated Approved!"
#    redirect_to comments_path
#  end
#
#  def reject
#    @comment.rejected
#    flash[:success] = "comment Moderated Rejected"
#    redirect_to comments_path
#  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.create(params[:comment])
    @comment.moderated = Comment::DEFAULT
    @comment.user_id  = current_user.id
    # @comment  = Comment.new(params[:comment])
    if @comment.save
      flash[:success] = "comment added"
      redirect_to story_path(params[:story_id])
      #redirect_to root_path
    else
      #   render 'pages/home'
    end
  end

  def destroy
    @comment.destroy
    redirect_back_or root_path
  end

  def show
    @story = Story.find(params[:id])
    @current_comments = @story.comments
    @comment = Comment.new if signed_in?
  end

  def upvote
    @comment.upvote
 #  p @comment.votes
     respond_to do |format|
      format.html {redirect_to story_path(@comment.story)}
      format.js{
        render :update do |page|
          page.replace_html("vote_#{@comment.id}",:partial => '/comments/votes', :locals => {:story => @comment.story, :comment => @comment})
        end
      }
    end
  end

  def downvote 
    @comment.downvote
     respond_to do |format|
     format.html {redirect_to story_path(@comment.story)}
      format.js{
        render :update do |page|
          page.replace_html("vote_#{@comment.id}",:partial => '/comments/votes', :locals => {:story => @comment.story, :comment => @comment})
        end
      }
    end
  end

  def find_comment
    @comment = Comment.find(params[:id]) if params[:id]
  end

  private :find_comment
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_votes.html.erb
<%= link_to (image_tag("greenarrow.gif", :size=>"17x17")), upvote_story_comment_url(story,comment), :remote => true %> <br/>
votes&nbsp;<%=comment.votes%><br/>
<%=link_to  (image_tag("redarrow.gif", :size=>"17x17")), downvote_story_comment_url(story,comment), :remote => true %>

app/views/comments/create.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">Post a Comment</h1>
        <%= render('shared/comment_form') %>
         </td>
       </tr>
  </table>
<% else %>
<h1>Autoworker Community</h1>
<p>
  This is the home page for the <a href="http://autoworker.com/">autoworker community</a> autoworker communitylication.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<table>
  <tr>
  <table class="micropost" summary="comments listing">
    <% @comments.each do |comment| %>
      <tr>
        <td class="main"> <%=comment.comment_text%></td>
        <td><%=comment.created_at%></td>
        <td>
          <%= link_to "Approve", approve_comment_path(comment) %>&nbsp;|&nbsp;
          <%= link_to "Reject", reject_comment_path(comment) %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/comments/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<h1>hi this is new.html in comments controller</h1>
<%= render 'shared/comment_form' %>

app/views/comments/show.html.erb
<table>  
  <tr>
  <table class="micropost" summary="comments listing">
    <% @current_comments.each do |comment| %>
      <tr>
        <td class="main"> <%=comment.comment_text%>
          <br> <font size="1">  Posted <%= time_ago_in_words(comment.created_at) %> ago.</font>
          <br>

      </tr>
    <% end %>
  </table>
  <%= render 'shared/comment_form' %>