config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
    end
  end

  resources :stories do
    member do
      get  :upvote, :downvote
    end
    resources :comments do
      member do
        get :upvote, :downvote
      end
    end
  end

  resources :comments do
    member do
      get :approve, :reject
    end
    collection do
      get :index
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy] do
    collection do
      get :forgot_password, :new_password, :update_reset_password
      post :send_reset_password, :reset_new_password
    end
  end
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
  root :to => "pages#home"

   match '/unsigned_retiree', :to => 'pages#unsigned_retiree'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/poststory', :to => 'pages#poststory'
  match '/postcomment', :to => 'comments#create'
  match '/retiree', :to => 'retirees#index'

  resources :retirees do
    collection do
      post :find_retiree
    end
  end
  get "retiree/index"
  get "retiree/update"
  get "retiree/delete"
  get "retiree/create"
  get "comments/create"
  get "comments/destroy"
  get "comments/show"

end

app/views/pages/_votes.html.erb
<%= link_to (image_tag("greenarrow.gif", :size=>"18x18")), upvote_story_path(story), :remote => true %> <br/>
votes&nbsp;<%=story.votes%><br/>
<%=link_to  (image_tag("redarrow.gif", :size=>"18x18")), downvote_story_path(story), :remote => true %>

app/views/pages/about.html.erb
<h2>About Us</h2>
<p>
  <a href="http://autoworker.com/">Autoworker Community</a>
</p>

app/views/pages/contact.html.erb
<h3>Contact</h3>
<%#*<p>%>
  <%#*autoworker community%>
  <%#*<a href="http://autoworker.com/feedback">feedback page</a>.%>
<%#*</p>%>
<p>
  <%= mail_to "autoworker1@gmail.com", "contact us", :encode => "hex" %>
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  autoworker community
  <a href="http://railstutorial.org/help">autoworker community</a>.
  autoworker community
  <a href="http://autoworker.com/">autoworker community</a>.
</p>

app/views/pages/home.html.erb
<%# if signed_in? %>
<table class="pretty-table-new" summary="stories listing">
  <% if not signed_in? %>
    <tr><td colspan="4"> <%= link_to "Sign in", signin_path, :class => "signin_button2 round" %>  | <%= link_to "Sign up now!", signup_path, :class => "signup_button2 round" %>
      </td></tr>
  <%end%>
  <tr><td background-color=#FFFF00; colspan=5;>
    suggestion: quickly scan the main story and keep the discussion here - add quality comments</td></tr>
  <% @stories.each do |story|  %>
    <tr class="story_tr round"><td><%if story.photo.exists? then %>
          <%=image_tag story.photo.url(:thumb), :size => "80x80" %></td>
      <% else %>
          <%=image_tag("defaultcar.jpg",  :size => "80x80") %></td>
        <% end %>
      <td id="vote_<%=story.id%>" class="votes_box round">
        <%= render :partial => 'pages/votes', :locals => {:story => story} %>
      </td>
      <td><%=link_to  story.title, story_path(story), :class =>"story_url"%><a href="<%= story.url %>" font size="-2">[read more]</a>
        <br/><%= story.teaser %>
        <br/> <font size="1">  Posted by <%= story.user.name %>&nbsp;<%= time_ago_in_words(story.created_at) %> ago.</font>
        <br/> <%=Comment.moderated(story.id).count %>
        <%= link_to "Comments", story_path(story)%></td>
    </tr>
  <% end %>
</table>
<%#*</tr>%>
<%#*</table>%>

<%# else %>



<%# end %>

app/views/pages/poststory.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">Post a Story</h1>
        <%= render('shared/story_form') %>
         </td>
       </tr>
  </table>
<% else %>
<h1>Autoworker Community</h1>
<p>
  This is the home page for the <a href="http://autoworker.com/">autoworker community</a> autoworker communitylication.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>