config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
    end
  end

  resources :stories do
    member do
      get  :upvote, :downvote
    end
    resources :comments do
      member do
        get :upvote, :downvote
      end
    end
  end

  resources :comments do
    member do
      get :approve, :reject
    end
    collection do
      get :index
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy] do
    collection do
      get :forgot_password, :new_password, :update_reset_password
      post :send_reset_password, :reset_new_password
    end
  end
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
  root :to => "pages#home"

   match '/unsigned_retiree', :to => 'pages#unsigned_retiree'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/poststory', :to => 'pages#poststory'
  match '/postcomment', :to => 'comments#create'
  match '/retiree', :to => 'retirees#index'

  resources :retirees do
    collection do
      post :find_retiree
    end
  end
  get "retiree/index"
  get "retiree/update"
  get "retiree/delete"
  get "retiree/create"
  get "comments/create"
  get "comments/destroy"
  get "comments/show"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav id="nav">
    <ul>
      <li>@copyright 2011</li>
      <li>&nbsp;&nbsp;</li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<%#= link_to logo, root_path %>
<%#=image_tag("awlogo51.gif", :size => "680x150") %>
<!--<%= link_to image_tag("logo1.jpeg", :size=>"100x50"), root_path %> -->
<head>
<div class="round" style="margin-top:1px;background-color: #eeeeee;float:right;width:100%;height:0px;">
<% if signed_in? %>
  <span style="float:right;margin-right:10px;margin-top:20px;">
    Welcome <%=current_user.email%>&nbsp;|&nbsp;<%= link_to "Sign out", signout_path %>
  </span>
  <% end %>
</div>
</head>
<div class="clear">
</div>
 <!-- <nav class="round">
    <ul>
      <li><%= link_to "Top Stories", root_path %></li>
      <% if signed_in? %>

                      <% if false%>  
                          <li> <%= link_to "Profile", current_user %> </li> 
                          <li><%= link_to "Users", users_path %></li> 
                      <% end %>

        <li><%= link_to "Post Story", poststory_path %></li>
        <li><%= link_to "Retiree", retiree_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
       
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
    </nav> -->
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<%#= init_tinymce_hammer_if_required %>
<%#= tinyMCE.init({:force_p_newlines =>"true"})   %>
    <title><%= title %></title>
    <meta name="description" content="<%= meta_description %>" />
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
<%#= javascript_include_tag :defaults, 'jquery-ui-1.8.10.custom.min.js','jrails.js','jquery.min.js','tiny_mce/tiny_mce.js' %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
    <%= javascript_include_tag "rails" %>
    <%= javascript_include_tag "application" %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7483197-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <body>
    <%= link_to image_tag("awlogo52.gif",:style =>"width:100%;", :alt =>"autoworker"), root_path %>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
      <!--  <nav class="round" style="font-color:solid white;font-size:12px;font-weight:bold;"> -->
      <nav id="nav">
          <ul>
            <li><%= link_to "Top Stories      ", root_path %></li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li><%= link_to "Retirees     ", retiree_path %></li>
             <li>&nbsp;&nbsp;</li>
            <% if signed_in? %>
              <% if false%>
                <li> <%= link_to "Profile", current_user %> </li>
                <li><%= link_to "Users", users_path %></li>
                <li><%=link_to "Moderate Comments", comments_path  if current_user.admin? %></li>
              <% end %>
              <li><%= link_to "Post Story", poststory_path %></li>
               <li>&nbsp;</li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% end %>
          </ul>
        </nav>
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>